name: 🚀 Deploy MONARCH2026©
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notificar Render
        run: curl -X POST ${{ secrets.RENDER_HOOK }}
